version: '3.7'

volumes:
  data-volume:

services:
  mongo:
    image: mongo
    container_name: mts-mongo
    hostname: mts-mongo
    stdin_open: true
    tty: true
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw3rd
 

networks:
  default:
    external:
      name: nat
